import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ComplianceAssessment, AssessmentResult, ComplianceFramework } from './complianceTypes';

// ── Colour palette (dark-to-light rendering for print) ────────────────────────

const COLORS = {
  navy:      [15,  23,  42]  as [number, number, number],
  cyan:      [6,   182, 212] as [number, number, number],
  emerald:   [16,  185, 129] as [number, number, number],
  amber:     [245, 158, 11]  as [number, number, number],
  red:       [239, 68,  68]  as [number, number, number],
  slate:     [100, 116, 139] as [number, number, number],
  lightGray: [248, 250, 252] as [number, number, number],
  white:     [255, 255, 255] as [number, number, number],
};

function statusColor(s: string): [number, number, number] {
  if (s === 'compliant')    return COLORS.emerald;
  if (s === 'partial')      return COLORS.amber;
  if (s === 'noncompliant') return COLORS.red;
  return COLORS.slate;
}

function statusLabel(s: string): string {
  if (s === 'compliant')      return 'Compliant';
  if (s === 'partial')        return 'Partial';
  if (s === 'noncompliant')   return 'Non-Compliant';
  if (s === 'not_applicable') return 'N/A';
  return 'Not Reviewed';
}

function formatDate(iso: string | null | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric',
  });
}

function scoreGrade(score: number): string {
  if (score >= 85) return 'A';
  if (score >= 70) return 'B';
  if (score >= 55) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

// ── Page helpers ──────────────────────────────────────────────────────────────

function addPageBorder(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...COLORS.cyan);
  doc.setLineWidth(0.5);
  doc.rect(8, 8, w - 16, h - 16);
}

function addHeader(doc: jsPDF, title: string, pageNum: number, totalPages: number) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, 0, w, 18, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.cyan);
  doc.setFont('helvetica', 'bold');
  doc.text('CyberRisk IQ  ·  by Regorisk · ProGReC', 14, 11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.slate);
  doc.text(title, w / 2, 11, { align: 'center' });
  doc.text(`Page ${pageNum} of ${totalPages}`, w - 14, 11, { align: 'right' });
}

function addFooter(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, h - 12, w, 12, 'F');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.slate);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'This report is generated by CyberRisk IQ. It is confidential and intended for the named organisation only.',
    w / 2, h - 4.5,
    { align: 'center' },
  );
}

// ── Certificate page ──────────────────────────────────────────────────────────

function addCertificatePage(
  doc: jsPDF,
  framework: ComplianceFramework,
  assessment: ComplianceAssessment,
  results: AssessmentResult[],
) {
  const w = doc.internal.pageSize.getWidth();
  const score = assessment.overall_score ?? 0;
  const grade = scoreGrade(score);
  const compliant    = results.filter(r => r.status === 'compliant').length;
  const partial      = results.filter(r => r.status === 'partial').length;
  const noncompliant = results.filter(r => r.status === 'noncompliant').length;
  const applicable   = results.filter(r => r.status !== 'not_applicable').length;

  // Background
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, 0, w, doc.internal.pageSize.getHeight(), 'F');

  // Decorative top stripe
  doc.setFillColor(...COLORS.cyan);
  doc.rect(0, 0, w, 4, 'F');

  // Watermark grade
  doc.setFontSize(180);
  doc.setTextColor(255, 255, 255);
  doc.setGState(doc.GState({ opacity: 0.04 }));
  doc.setFont('helvetica', 'bold');
  doc.text(grade, w / 2, 180, { align: 'center' });
  doc.setGState(doc.GState({ opacity: 1 }));

  // Logo / title area
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.cyan);
  doc.setFont('helvetica', 'bold');
  doc.text('CYBERRISK IQ  ·  REGORISK · PROGRC', w / 2, 30, { align: 'center' });

  doc.setFontSize(22);
  doc.setTextColor(...COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.text('CERTIFICATE OF COMPLIANCE', w / 2, 50, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.slate);
  doc.setFont('helvetica', 'normal');
  doc.text('This document certifies that the following assessment has been completed', w / 2, 60, { align: 'center' });

  // Divider
  doc.setDrawColor(...COLORS.cyan);
  doc.setLineWidth(0.3);
  doc.line(30, 65, w - 30, 65);

  // Organisation block
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.text('Acme Financial Corp', w / 2, 78, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.slate);
  doc.setFont('helvetica', 'normal');
  doc.text(`has completed a compliance assessment against`, w / 2, 86, { align: 'center' });

  doc.setFontSize(18);
  doc.setTextColor(...COLORS.cyan);
  doc.setFont('helvetica', 'bold');
  doc.text(`${framework.name} ${framework.version}`, w / 2, 98, { align: 'center' });

  // Score ring area — drawn as concentric circles
  const cx = w / 2;
  const cy = 138;

  doc.setFillColor(20, 30, 55);
  doc.circle(cx, cy, 28, 'F');

  const scoreColor = score >= 85 ? COLORS.emerald : score >= 60 ? COLORS.amber : COLORS.red;
  doc.setDrawColor(...scoreColor);
  doc.setLineWidth(3);
  doc.circle(cx, cy, 26);

  doc.setFontSize(28);
  doc.setTextColor(...scoreColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`${score}%`, cx, cy + 4, { align: 'center' });

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.slate);
  doc.setFont('helvetica', 'normal');
  doc.text('OVERALL SCORE', cx, cy + 12, { align: 'center' });

  // Grade badge
  doc.setFillColor(...scoreColor);
  doc.roundedRect(cx + 32, cy - 10, 18, 18, 3, 3, 'F');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.text(grade, cx + 41, cy + 4, { align: 'center' });

  // Stats row
  const statsY = 175;
  const statCols = [
    { label: 'Compliant',     value: compliant,    color: COLORS.emerald },
    { label: 'Partial',       value: partial,      color: COLORS.amber   },
    { label: 'Non-Compliant', value: noncompliant, color: COLORS.red     },
    { label: 'Applicable',    value: applicable,   color: COLORS.cyan    },
  ];
  const colW = (w - 60) / statCols.length;
  statCols.forEach((col, i) => {
    const x = 30 + i * colW + colW / 2;
    doc.setFillColor(20, 30, 55);
    doc.roundedRect(30 + i * colW, statsY - 10, colW - 4, 22, 3, 3, 'F');
    doc.setFontSize(16);
    doc.setTextColor(...col.color);
    doc.setFont('helvetica', 'bold');
    doc.text(String(col.value), x, statsY + 2, { align: 'center' });
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.slate);
    doc.setFont('helvetica', 'normal');
    doc.text(col.label, x, statsY + 9, { align: 'center' });
  });

  // Divider
  doc.setDrawColor(...COLORS.slate);
  doc.setLineWidth(0.2);
  doc.line(30, 203, w - 30, 203);

  // Meta info
  const metaY = 214;
  const meta = [
    ['Framework',    `${framework.name} v${framework.version}`],
    ['Category',     framework.category],
    ['Assessed by',  assessment.assessed_by],
    ['Assessment date', formatDate(assessment.completed_at)],
    ['Certificate ref', `CRQ-${assessment.id.slice(0, 8).toUpperCase()}`],
    ['Valid until',  formatDate(
      assessment.completed_at
        ? new Date(new Date(assessment.completed_at).setFullYear(
            new Date(assessment.completed_at).getFullYear() + 1
          )).toISOString()
        : null
    )],
  ];

  const halfLen = Math.ceil(meta.length / 2);
  meta.forEach(([label, value], i) => {
    const col = i < halfLen ? 0 : 1;
    const row = i < halfLen ? i : i - halfLen;
    const x = col === 0 ? 30 : w / 2 + 5;
    const y = metaY + row * 12;
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.slate);
    doc.setFont('helvetica', 'normal');
    doc.text(label.toUpperCase(), x, y);
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.white);
    doc.setFont('helvetica', 'bold');
    doc.text(value, x, y + 5);
  });

  // Bottom stripe
  doc.setFillColor(...COLORS.cyan);
  doc.rect(0, doc.internal.pageSize.getHeight() - 4, w, 4, 'F');
}

// ── Executive summary page ────────────────────────────────────────────────────

function addSummaryPage(
  doc: jsPDF,
  framework: ComplianceFramework,
  assessment: ComplianceAssessment,
  results: AssessmentResult[],
  pageNum: number,
  totalPages: number,
) {
  addHeader(doc, 'Executive Summary', pageNum, totalPages);
  addFooter(doc);
  addPageBorder(doc);

  let y = 26;
  const w = doc.internal.pageSize.getWidth();

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.navy);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(...COLORS.slate);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `This report summarises the compliance assessment for ${framework.name} ${framework.version} ` +
    `conducted by ${assessment.assessed_by} on ${formatDate(assessment.completed_at)}. ` +
    `The assessment covered ${results.length} controls across ${[...new Set(results.map(r => r.control?.domain).filter(Boolean))].length} domains.`,
    14, y,
    { maxWidth: w - 28 },
  );
  y += 18;

  // Key metrics table
  const applicable   = results.filter(r => r.status !== 'not_applicable');
  const compliant    = applicable.filter(r => r.status === 'compliant').length;
  const partial      = applicable.filter(r => r.status === 'partial').length;
  const noncompliant = applicable.filter(r => r.status === 'noncompliant').length;
  const score        = assessment.overall_score ?? 0;

  autoTable(doc, {
    startY: y,
    head:   [['Metric', 'Value']],
    body: [
      ['Framework',              `${framework.name} ${framework.version}`],
      ['Category',               framework.category],
      ['Overall Score',          `${score}% (Grade ${scoreGrade(score)})`],
      ['Controls Assessed',      String(applicable.length)],
      ['Compliant',              `${compliant} (${applicable.length ? Math.round(compliant / applicable.length * 100) : 0}%)`],
      ['Partial',                `${partial} (${applicable.length ? Math.round(partial / applicable.length * 100) : 0}%)`],
      ['Non-Compliant',          `${noncompliant} (${applicable.length ? Math.round(noncompliant / applicable.length * 100) : 0}%)`],
      ['Assessment Date',        formatDate(assessment.completed_at)],
      ['Assessed By',            assessment.assessed_by],
      ['Certificate Reference',  `CRQ-${assessment.id.slice(0, 8).toUpperCase()}`],
    ],
    theme:      'striped',
    headStyles: { fillColor: COLORS.navy, textColor: COLORS.white, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Domain breakdown
  const domains = [...new Set(results.map(r => r.control?.domain).filter(Boolean))] as string[];
  if (domains.length > 0) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.navy);
    doc.setFont('helvetica', 'bold');
    doc.text('Score by Domain', 14, y);
    y += 4;

    const domainRows = domains.map(d => {
      const dr = results.filter(r => r.control?.domain === d && r.status !== 'not_applicable');
      const ds = dr.length > 0
        ? Math.round(dr.reduce((s, r) => {
            if (r.status === 'compliant')    return s + (r.score ?? 100);
            if (r.status === 'partial')      return s + (r.score ?? 50);
            if (r.status === 'noncompliant') return s + (r.score ?? 0);
            return s;
          }, 0) / dr.length)
        : 0;
      const dc = dr.filter(r => r.status === 'compliant').length;
      const dp = dr.filter(r => r.status === 'partial').length;
      const dn = dr.filter(r => r.status === 'noncompliant').length;
      return [d, String(dr.length), `${dc}`, `${dp}`, `${dn}`, `${ds}%`];
    });

    autoTable(doc, {
      startY: y,
      head:   [['Domain', 'Controls', 'Compliant', 'Partial', 'Non-Compliant', 'Score']],
      body:   domainRows,
      theme:  'striped',
      headStyles: { fillColor: COLORS.navy, textColor: COLORS.white, fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
  }
}

// ── Control detail pages ──────────────────────────────────────────────────────

function addControlsPage(
  doc: jsPDF,
  results: AssessmentResult[],
  pageNum: number,
  totalPages: number,
) {
  addHeader(doc, 'Control Assessment Detail', pageNum, totalPages);
  addFooter(doc);
  addPageBorder(doc);

  const rows = results
    .filter(r => r.status !== 'not_applicable')
    .map(r => [
      r.control?.control_id ?? '—',
      r.control?.title ?? '—',
      r.control?.domain ?? '—',
      statusLabel(r.status),
      r.score != null ? `${r.score}%` : '—',
      (r.notes ?? '—').slice(0, 120),
    ]);

  autoTable(doc, {
    startY: 24,
    head:   [['Control', 'Title', 'Domain', 'Status', 'Score', 'Finding']],
    body:   rows,
    theme:  'striped',
    headStyles: { fillColor: COLORS.navy, textColor: COLORS.white, fontSize: 7 },
    bodyStyles: { fontSize: 7, minCellHeight: 8 },
    columnStyles: {
      0: { cellWidth: 18 },
      1: { cellWidth: 42 },
      2: { cellWidth: 25 },
      3: { cellWidth: 22 },
      4: { cellWidth: 14 },
      5: { cellWidth: 'auto' },
    },
    didParseCell: (data) => {
      if (data.column.index === 3 && data.section === 'body') {
        const val = String(data.cell.raw ?? '');
        data.cell.styles.textColor =
          val === 'Compliant'    ? COLORS.emerald :
          val === 'Partial'      ? COLORS.amber   :
          val === 'Non-Compliant'? COLORS.red      :
          COLORS.slate;
        data.cell.styles.fontStyle = 'bold';
      }
    },
    margin: { left: 14, right: 14 },
  });
}

// ── Remediation action plan page ──────────────────────────────────────────────

function addRemediationPage(
  doc: jsPDF,
  results: AssessmentResult[],
  pageNum: number,
  totalPages: number,
) {
  addHeader(doc, 'Remediation Action Plan', pageNum, totalPages);
  addFooter(doc);
  addPageBorder(doc);

  const gaps = results.filter(r => r.status === 'noncompliant' || r.status === 'partial');

  if (gaps.length === 0) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.emerald);
    doc.setFont('helvetica', 'bold');
    doc.text('No remediation actions required — all controls are compliant.', 14, 40);
    return;
  }

  const rows = gaps.map((r, i) => [
    String(i + 1),
    r.control?.control_id ?? '—',
    r.control?.title ?? '—',
    statusLabel(r.status),
    r.score != null ? `${r.score}%` : '—',
    (r.evidence ?? r.notes ?? 'No remediation noted.').slice(0, 150),
    'Open',
  ]);

  autoTable(doc, {
    startY: 24,
    head:   [['#', 'Control', 'Title', 'Status', 'Score', 'Recommended Remediation', 'Status']],
    body:   rows,
    theme:  'striped',
    headStyles: { fillColor: COLORS.navy, textColor: COLORS.white, fontSize: 7 },
    bodyStyles: { fontSize: 7, minCellHeight: 10 },
    columnStyles: {
      0: { cellWidth: 8  },
      1: { cellWidth: 18 },
      2: { cellWidth: 38 },
      3: { cellWidth: 22 },
      4: { cellWidth: 14 },
      5: { cellWidth: 'auto' },
      6: { cellWidth: 14 },
    },
    didParseCell: (data) => {
      if (data.column.index === 3 && data.section === 'body') {
        const val = String(data.cell.raw ?? '');
        data.cell.styles.textColor = val === 'Partial' ? COLORS.amber : COLORS.red;
        data.cell.styles.fontStyle = 'bold';
      }
    },
    margin: { left: 14, right: 14 },
  });
}

// ── Main export function ───────────────────────────────────────────────────────

export async function generateComplianceReport(
  framework:  ComplianceFramework,
  assessment: ComplianceAssessment,
  results:    AssessmentResult[],
): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const totalPages = 4;

  // Page 1 — Certificate
  addCertificatePage(doc, framework, assessment, results);

  // Page 2 — Executive summary
  doc.addPage();
  addSummaryPage(doc, framework, assessment, results, 2, totalPages);

  // Page 3 — Control detail
  doc.addPage();
  addControlsPage(doc, results, 3, totalPages);

  // Page 4 — Remediation plan
  doc.addPage();
  addRemediationPage(doc, results, 4, totalPages);

  const ref = `CRQ-${assessment.id.slice(0, 8).toUpperCase()}`;
  const date = assessment.completed_at
    ? new Date(assessment.completed_at).toISOString().split('T')[0]
    : new Date().toISOString().split('T')[0];

  doc.save(`${framework.name.replace(/\s+/g, '-')}_${ref}_${date}.pdf`);
}